//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_PTUDTTHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienBanViPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienBanViPham()
        {
            this.LoiViPhams = new HashSet<LoiViPham>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> TongDiemTru { get; set; }
        public Nullable<System.DateTime> ThoiGianViPham { get; set; }
        public Nullable<int> HDNopPhat { get; set; }
        public Nullable<int> BangLai_id { get; set; }
    
        public virtual BangLai BangLai { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoiViPham> LoiViPhams { get; set; }
    }
}
