//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_PTUDTTHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.BienBanViPhams = new HashSet<BienBanViPham>();
            this.YeuCauDangKyXes = new HashSet<YeuCauDangKyXe>();
            this.YeuCauDangKyXes1 = new HashSet<YeuCauDangKyXe>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<int> HinhThucThanhToan_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienBanViPham> BienBanViPhams { get; set; }
        public virtual HinhThucThanhToan HinhThucThanhToan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCauDangKyXe> YeuCauDangKyXes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCauDangKyXe> YeuCauDangKyXes1 { get; set; }
    }
}
