//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_PTUDTTHD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLHTGTEntities : DbContext
    {
        public QLHTGTEntities()
            : base("name=QLHTGTEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangLai> BangLais { get; set; }
        public virtual DbSet<BienBanViPham> BienBanViPhams { get; set; }
        public virtual DbSet<CanBo> CanBoes { get; set; }
        public virtual DbSet<HinhThucThanhToan> HinhThucThanhToans { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<LoaiXe> LoaiXes { get; set; }
        public virtual DbSet<LoiViPham> LoiViPhams { get; set; }
        public virtual DbSet<MucPhiCapBien> MucPhiCapBiens { get; set; }
        public virtual DbSet<MucPhiTruocBa> MucPhiTruocBas { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
        public virtual DbSet<YeuCauDangKyXe> YeuCauDangKyXes { get; set; }
    }
}
