//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_PTUDTTHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        public int ID { get; set; }
        public string SoKhung { get; set; }
        public string SoMay { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public Nullable<int> LoaiXe_id { get; set; }
        public Nullable<int> NguoiDung_id { get; set; }
        public string BienSo { get; set; }
    
        public virtual LoaiXe LoaiXe { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
